plugins:
  - rubocop-rails
  - rubocop-capybara

RSpecRails/AvoidSetupHook:
  Enabled: true

RSpecRails/HaveHttpStatus:
  Enabled: true

RSpecRails/InferredSpecType:
  Enabled: true

###############################################################################
##                           Customizations                                  ##
###############################################################################
