plugins:
  - rubocop-rails
  - rubocop-capybara

RSpec/Rails/AvoidSetupHook:
  Enabled: true

RSpec/Rails/HaveHttpStatus:
  Enabled: true

RSpec/Rails/InferredSpecType:
  Enabled: true

###############################################################################
##                           Customizations                                  ##
###############################################################################
