plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

RSpecRails/AvoidSetupHook:
  Enabled: true

RSpecRails/HaveHttpStatus:
  Enabled: true

RSpecRails/InferredSpecType:
  Enabled: true

###############################################################################
##                           Customizations                                  ##
###############################################################################
